### ISSUE TITLE
Release版本退出时报异常

### ISSUE THREAD

**Issue by chengf2018** [pili-engineering/QNRTC-Windows#11]
编译Release版本时，退出报了一个异常。找了好久，发现问题出现在CRtcDemoDlg::OnBnClickedButtonJoin()方法中，_join_room_thread并没有调用join或者detach方法，导致报异常，建议解决方法：CRtcDemoDlg::OnDestroy()方法中添加:
if (_join_room_thread.joinable()) {
		_join_room_thread.join();
}

**Comment by cgb0210** [comment]
了解，可能窗体关闭太快，而此时获取 RoomToken 的线程还没有退出（可能是网络问题），从而导致线程未退出便被释放了，导致异常。

**Comment by cgb0210** [comment]
新版本已添加
